# Generated by Django 4.0.4 on 2022-05-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20191216_0937'),
        ('users', '0002_alter_user_avatar_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favs',
        ),
        migrations.AddField(
            model_name='user',
            name='fav',
            field=models.ManyToManyField(related_name='fav', to='rooms.room'),
        ),
    ]
