# Generated by Django 4.0.4 on 2022-05-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_fav_user_favs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favs',
        ),
    ]
