# Generated by Django 4.0.4 on 2022-05-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20191216_0937'),
        ('users', '0005_remove_user_favs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favs',
            field=models.ManyToManyField(null=True, related_name='favs', to='rooms.room'),
        ),
    ]
